### ISSUE TITLE
DoH support

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#117] opened 2022-01-13 08:48 UTC
Hi so nowadays most dns providers have Dns over https support, was wondering if it's possible to have a bancuh doh version. thx

**Comment by ragibkl** [comment] 2022-01-14 01:19
Yeah, that would be good to have! I don't know how to do this yet. If you happen across any docs or guides online, do paste the links here.

**Comment by ragibkl** [comment] 2022-01-15 04:19
Found some notes:
- https://www.aaflalo.me/2018/10/tutorial-setup-dns-over-https-server/
- https://dnsdist.org/
- https://www.linuxbabe.com/ubuntu/dns-over-https-doh-resolver-ubuntu-dnsdist

I think this is worth doing. I'll try spend some time on this.

**Comment by ragibkl** [comment] 2022-02-20 06:46
Hi @Tomatoide ,

I created a test DNS server for this. Also pull request is [here](https://github.com/ragibkl/adblock-dns-server/pull/121) if you are interested.

Could you please test the server?

DNS:
- domain: dns1.test.ragibkl.cloudns.org
- ipv4: 163.172.160.117
- ipv6: 2001:bc8:628:843::1

DoT:
- domain: dns1.test.ragibkl.cloudns.org

DoH:
- url: https://dns1.test.ragibkl.cloudns.org/dns-query


Drawbacks:
- logs viewer not working, since requests are handled by `dnsdist` instead of `bind` directly. We can maybe enhance logs-viewer to work with dnsdist in future.
- http null server not working since port 80 is used by the certbot. I wasn't using this anyway.
- rate limit won't work so well, need to turn off and enable dnsdist to handle this.

**Comment by Tomatoide** [comment] 2022-02-20 11:28
Great! I will test the doh and report any findings, thank you once again

**Comment by ragibkl** [comment] 2022-02-20 12:33
@Tomatoide ,

If you have time, you can test the DoT as well. On Android phones, there is setting for `Private DNS`, which if you input the server domain, it will use it with DoT protocol.

Thanks!

**Comment by Tomatoide** [comment] 2022-02-20 19:04
So far so good 👍 looking forward for the final version and addressing drawbacks

**Comment by Tomatoide** [comment] 2022-02-26 15:47
@ragibkl Nice it works 👍

**Comment by ragibkl** [comment] 2022-02-27 09:11
@Tomatoide , I'm activating both fr-dns1 and fr-dns2 as well.
See: https://blog.bancuh.com/adblock-dns/adblock-dns-quickstart/

Do test them and let me know any issues.

**Comment by Tomatoide** [comment] 2022-02-27 09:28
Awesome! thanks for your amazing work @ragibkl initial testing is promising and all well 👍

**Comment by ragibkl** [comment] 2022-03-03 01:04
Hi @Tomatoide ,

It's been a few days. I haven't used the DoH much, but I've been using the DoT on my Android and everything seems fine. It's nice to see the adblock works on the phone, even when I'm outside my home WiFi.

I think, let's call this feature as completed. I'll close this issue now. Since this is a supported feature now, if anything is not working as intended, we should treat them as bugs, so you can just file them as new issues separately.

BTW, if you are still using the test server here: https://github.com/ragibkl/adblock-dns-server/issues/117#issuecomment-1046174769, please change to the production servers listed in here: https://blog.bancuh.com/adblock-dns/adblock-dns-quickstart/ instead. I will turn it off in 2 days.

Have a good day!

**Closed by ragibkl** 2022-03-03 01:04 UTC
