### ISSUE TITLE
Tried to start server on DigitalOcean droplet

### ISSUE THREAD

**Issue by DeathWithKebab** [ragibkl/adblock-dns-server#65] opened 2020-12-05 21:08 UTC
>root@ubuntu-s-1vcpu-1gb-fra1-01:~/adblock-dns-server# ./start.sh
Pulling adblock_dns  ... done
Pulling adblock_http ... done
Pulling logs_viewer  ... done
Removing adblock-dns-server_adblock_dns_1
Recreating dd2cced908c8_adblock-dns-server_adblock_dns_1 ...
Recreating dd2cced908c8_adblock-dns-server_adblock_dns_1 ... error
Starting adblock-dns-server_logs_viewer_1                ... done
ERROR: for dd2cced908c8_adblock-dns-server_adblock_dns_1  Cannot start service adblock_dns: driver failed programming external connectivity on endpoint adblock-dns-server_adblock_dns_1 (f3496794e507c25e080c696277e5bb9e100689caadb7d4b71c1241267628dfdb): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use
ERROR: for adblock_dns  Cannot start service adblock_dns: driver failed programming external connectivity on endpoint adblock-dns-server_adblock_dns_1 (f3496794e507c25e080c696277e5bb9e100689caadb7d4b71c1241267628dfdb): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.

Hello, got the above error after trying to run it.... wondering if I did all right... the .env file has just the extension... no name, is that right? Left domain and ipv6 in the file blank.

**Comment by ragibkl** [comment] 2020-12-07 09:33
Hi @DeathWithKebab , thanks for reaching out.

It turns out that, modern linux distros using systemd also spin up a local dns service called `systemd-resolved`. This local dns is meant to reduce dns requests on the system to improve performance. However, since it is also using port `:53`, it will conflict with our adblock dns server.

Therefore, we need to disable it. I haven't documented the steps for that just yet, but it goes roughly as follows for `ubuntu 20.04`:

1. Disable and stop the systemd-resolved service:

```shell
sudo systemctl disable systemd-resolved.service
sudo systemctl stop systemd-resolved
```

2. Edit the following file: `file /etc/resolv.conf`, maybe replacing with google dns
```shell
nameserver 8.8.8.8
nameserver 8.8.4.4
```

3. Try the start script again.

Additional references:
- https://gist.github.com/zoilomora/f7d264cefbb589f3f1b1fc2cea2c844c
- https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu

**Comment by DeathWithKebab** [comment] 2020-12-07 09:35
I'll try out as soon I'll get to my PC. I'll let you know

**Comment by DeathWithKebab** [comment] 2020-12-07 10:41
Worked out like a charm, the server is on!

The only problem is during testing fase nslookup could reach no server

**Comment by ragibkl** [comment] 2020-12-07 11:11
@DeathWithKebab , I'm glad it works out!

If you have any suggestions, or if you think there are better ways I could document the steps, do let me know.

Feel free to close this issue ticket if you believe that it is resolved for you.

**Comment by DeathWithKebab** [comment] 2020-12-07 11:36
@ragibkl 
The documentation is clear and got nothing to say about it!
wandering if I have to open another issue ticker or can I ask you directly here for the problem said in the last comment.

**Comment by ragibkl** [comment] 2020-12-07 11:51
I'm fine either way if the issue is closely related. For this ticket, I'd like to at least add the troubleshooting steps here in the README file, that way future users have less trouble. Maybe we can close this ticket after that.

Good luck with your server!!

**Comment by DeathWithKebab** [comment] 2020-12-07 12:04
Well, not sure if it's related to the machine I'm actually using or I got something wrong while I was setting it up. In the testing phase I tried 
`nslookup zedo.com <server public ip>`
the command returned as it can't reach the server.

**Comment by ragibkl** [comment] 2020-12-07 14:07
Is it at least running from inside the server? If you ssh into the server, run the following, do you see anything?
```shell
nslookup zedo.com 127.0.0.1
```

Also, do you see any logs while in the server?
```shell
docker-compose logs -f
```

**Comment by ragibkl** [comment] 2020-12-07 14:08
@DeathWithKebab , can I know what kind of specs did you provision for this server? The adblock dns container now loads about > 1.5 millions domains. It would take a minimum amount of RAM of 2 GiB to run this server.

**Comment by ragibkl** [comment] 2020-12-07 14:26
@DeathWithKebab , the other think I could think of, is maybe you have some rules in your Digitalocean firewall settings, that prevents any queries from hitting your server. You need to open up tcp/udp ports 53.

Otherwise, there could be some firewall software running inside your server itself. Maybe try find some guildes online on how to turn it off?

Can I know what OS you tried this with? If I have the time, I'll try setting up myself and see if I can reproduce the issue.

**Comment by DeathWithKebab** [comment] 2020-12-07 14:28
Hello! The server is Droplet by Digital Ocean on Ubuntu System, the latest one.

**Comment by DeathWithKebab** [comment] 2020-12-07 14:40
![immagine](https://user-images.githubusercontent.com/52661903/101363321-8cea7d80-38a1-11eb-96f3-b6ca621985c1.png)
Yes, it might be a memory shortage problem but the machine had no lag spike or other latencies while starting the server

**Comment by ragibkl** [comment] 2020-12-07 14:43
Try with 2 GiB or 3 GiB then. Maybe you'll get more stable server. 1GiB is too small.

If you really need to save on budget, you may try to setup swapfile. But I don't recommend this. I don't know if it will perform well.

**Comment by ragibkl** [comment] 2020-12-11 12:45
Hi @DeathWithKebab , Can I know if you managed to run the server? I'm updated the readme now, and would like to know if there is there is anything else missing in the readme that I should add to help future users.

**Comment by DeathWithKebab** [comment] 2020-12-11 13:08
Hello @ragibkl, I'm actually trying to set u the server from zero... I'll let you asap. Ty

**Comment by ragibkl** [comment] 2020-12-19 06:43
Doc updated here: https://github.com/ragibkl/adblock-dns-server/pull/66
Changes merged in.

**Comment by DeathWithKebab** [comment] 2021-01-14 09:33
Sorry for very late response.
First things first, happy new year.
I took all this time experimenting and trying your code on virtual machines, physical servers and finally decided that a little server was the best solution for me.
I read the updated readme and it's good and understandable. Thank you!

**Closed** 2021-01-14 09:38 UTC
