### ISSUE TITLE
Problem about the response to the webpage (GeoDNS/GeoIP compatibility)

### ISSUE THREAD

**Issue by phanluchoaofficial** [ragibkl/adblock-dns-server#46] opened 2020-04-20 00:35 UTC
Hello @ragibkl ,

My name is Hoa again, today I want to tell you I cannot access to any international websites through your dns or I load the page very slow. Such as, nimo.tv (This webpage is about live tream games ,...... but they response very slow to open the page when I use your DNS). Back then, I had suggested that you set up this 2 DNS server in Asia and forget about the foreign websites. Therefore, the speed of experience is not as expected. So can do anything to improve the speed of your dns on solve any international websites faster ??

Thanks !

**Comment by ragibkl** [comment] 2020-04-21 01:49
Hi @phanluchoaofficial , I believe you reported this issue earlier, but it could not be fixed at the time.

Is this website only slow if you use my DNS servers? Is it a lot faster if you use a different DNS server? like google?

**Comment by phanluchoaofficial** [comment] 2020-04-21 03:52
Yes, I have just got slow speed when using your DNS. When I use Google DNS they load faster than I think !

**Comment by ragibkl** [comment] 2020-04-21 03:59
I added a small patch [here](https://github.com/ragibkl/adblock-dns-server/commit/0fb713ee2dcfa90b85f4e245bc6ece621ce9ec65)

Please test it for a bit and let me know if performance improved or not.

I will find ideas for other approaches as well.

**Comment by phanluchoaofficial** [comment] 2020-04-21 04:06
Hello @ragibkl 

No now, I'm still load slow on that website !!

Here is sreenshot of ping to website:

![1456](https://user-images.githubusercontent.com/63760808/79824276-18210c80-83c0-11ea-89a7-71d935ecfe76.PNG)

**Comment by phanluchoaofficial** [comment] 2020-04-21 04:08
@ragibkl 

I think you need to deploy new dns server on USA !!! So they will load faster

**Comment by phanluchoaofficial** [comment] 2020-04-21 04:15
@ragibkl 

You can watch this video, I use google dns will ping so slow. But I use your DNS ping very high !!!

https://drive.google.com/file/d/11b4Gf4dmjFzfZ5A94ac5PANWtkr7qnZg/view?usp=sharing

**Comment by ragibkl** [comment] 2020-04-21 08:47
It seems like you are getting different IP address for the domain `nimo.tv`, depending on which dns you use:
Bancuh: 13.227.95.35 (Argentina)
Google: 13.225.103.75 (Hong Kong)

I think, the issue here is that Bancuh DNS is giving you IP of a far away server, while Google gives you IP closer to your location.

We can check [here](https://dnschecker.org/#A/nimo.tv) that they are using AWS, maybe with Elastic IP or something, so they have multiple IP Addresses around the world. I think for different location, you should ideally get and IP closer to your location.

This issue is not about DNS performance. This issue is about GeoIP and GeoDNS. So we should find a way to fix compatibility of Bancuh DNS with GeoDNS/GeoIP

**Comment by phanluchoaofficial** [comment] 2020-04-21 11:36
Hii @ragibkl ,
As I know, Google DNS is a Anycast DNS so they will have a lots of servers to response. About your DNS, its just have 1 IP so they will response slow !! Can you review and set your dns to anycast dns so its better for that website !!!

**Comment by ragibkl** [comment] 2020-04-22 03:10
Hi @phanluchoaofficial , 

I don't think DNS response time is the issue here. My DNS servers response should be good enough  for most applications.

I think, the problem is with GeoDNS compatibility. There are articles that discuss this, like [here](http://techgenix.com/dns-performance-best-practices/).
> For your network to properly take advantage of GeoDNS, you must ensure that for external zones, your users are using a DNS server that is close to them, ...

Problem with my DNS servers, is that they are based in Singapore which is a bit far from you. Google DNS don't have this problem.,They have servers everywhere, behind a single Anycast IP address. You are always using Google DNS closest to your location.

Setting up an Anycast DNS is not easy. It is also expensive. It is not worth the effort unless I have servers in every location.

A cheaper solution, is for you to rent a VPS server in your country, and setup this project for your own use. You can even share the VPS among friends and families. You could also try this in a Linux computer at home, or if on Windows, you can try Ubuntu Server inside a VM.

I'm not sure if there is a way to fix GeoDNS like this yet, so I'm still looking for other ideas.

**Comment by phanluchoaofficial** [comment] 2020-04-22 09:28
Hi @ragibkl ,

So, on my report. You dont have any idea how to fix them ??

**Comment by ragibkl** [comment] 2020-04-22 10:08
For now, I don't have any solution. The only way, I think is to setup a DNS server at each user location. That way, GeoDNS will work correctly. It might be worth to setup this in the future, if I can get some funding (donation?/sponsor?), and if we have more users.

The only other thing I want to try, is maybe to disable dns forwarding, and try to query the root dns servers directly. I'm not sure how much it will help though.

The other thing that you can do, is to hard code the ip address of nimo.tv, into your computer host file directly. This is a workaround, not a fix. It also only works for a single computer, where it is setup.
Example for Linux:
```
$ nslookup nimo.tv 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	nimo.tv
Address: 99.86.181.39
Name:	nimo.tv
Address: 99.86.181.99
Name:	nimo.tv
Address: 99.86.181.106
Name:	nimo.tv
Address: 99.86.181.93
```

and then your `/etc/hosts` file:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

99.86.181.39 nimo.tv
99.86.181.99 nimo.tv
99.86.181.106 nimo.tv
99.86.181.93 nimo.tv
```
There should be some similar guides for Windows as well.

**Comment by phanluchoaofficial** [comment] 2020-04-22 13:06
@ragibkl Hello,

As you said, you will remove dns forwarding and transfer to root server. If so, I can use your DNS at my default dns servers on my router ?? Or you disabled dns forwarding I cannot use them for solve my domain ????

**Comment by phanluchoaofficial** [comment] 2020-04-22 13:08
@ragibkl 

As you said, you tell that you need some fund to many users do ???

**Comment by phanluchoaofficial** [comment] 2020-04-22 13:11
@ragibkl 

I think you dont need to remove dns forwarding because I'm still using your dns as my default dns server on my modem. If you deleted is will affected my connection !!!

**Comment by ragibkl** [comment] 2020-04-23 01:58
Hi @phanluchoaofficial ,

Actually, when I said to remove DNS forwarding, I mean that we don't depend on Google DNS to make other queries. We configure the Bancuh DNS to query the root DNS directly. It will function the same as before, just that we let Bancuh DNS do query by itself.

I'm hoping that doing this will give more accurate IP closer to user location. However, I just realised that it will be the same. It will use the Bancuh DNS ip location (Singapore), so we still have the same problem.

**Comment by ragibkl** [comment] 2020-04-23 02:12
> As you said, you will need some fund to many users do ???

To achieve correct GeoDNS behaviour, it is best that the DNS is placed as close as possible to all users. However, that means that I need DNS servers in each location. It costs money.

1. Cheapest solution for me: Each user deploy their own DNS servers. That's why I created this project, so everyone can deploy their own. Maybe users can share the IP of their servers to me, I can publish on the site and help users find each other that way.

2. A bit more expensive for me: I deploy servers in each location. Servers cost money. Each servers will have different IP.

3. Even more expensive for me: I deploy servers in each location, behind Anycast IP. This will cost a lot more, I don't even know how to set this up yet.

I don't plan to ask money from people. I want to keep the servers free for as long as possible. If I become rich, I might do `2.` or `3.`, just for the fun of helping people. But now, it is a bit too expensive.

At the moment, I don't plan on expanding to more servers. I'm not even sure how far I can take project.

I plan to do the free stuff first, such as improving reliability, uptime, code improvements etc. I also haven't completed the different variants yet, which might be a very useful feature for people to use.

Then again, who knows. Maybe in future if a lot more people want to use the DNS, it might be worth to just keep expanding.

**Comment by phanluchoaofficial** [comment] 2020-04-23 10:55
@ragibkl Oke,

**Comment by ragibkl** [comment] 2020-04-23 11:16
@phanluchoaofficial , I want to test the theory that a different DNS location will perform better.

I want to test a server in tokyo. If you have time, please test the following DNS:
- 103.29.68.118
- 2400:8902::f03c:92ff:fe3e:46cd

**Comment by ragibkl** [comment] 2020-04-24 04:43
I'm closing this issue. Seems like we already cover the root cause of the issue, and identify potential solutions. Next action item, is to decide on the Tokyo server at https://github.com/ragibkl/adblock-dns-server/issues/53.

No other actions for now.

**Closed by ragibkl** 2020-04-24 04:43 UTC
